{% set version = "1.14.7-1" %}
{% set sha256 = "c5c7174151d0762d82f64f7d9e8f1c43755b7e4973eb9c9bd5ae36c311737838" %}
{% set version = "1.14.7-1" %}
{% set sha256 = "c5c7174151d0762d82f64f7d9e8f1c43755b7e4973eb9c9bd5ae36c311737838" %}

package:
  name: ros-rosbash
  version: {{ version.split("-")[0] }}

source:
  url: https://github.com/ros-gbp/ros-release/archive/release/melodic/rosbash/{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 0  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make  # [unix]
  host:
    - ros-conda-mutex * melodic
    - ros-conda-base
    - catkin_pkg
    - ros-catkin
  run:
    - ros-conda-mutex * melodic
    - ros-conda-base
    - ros-catkin
    - ros-rospack

test:
  requires:
    - rospkg
  commands:
    - export ROS_ROOT=$PREFIX && python -c "import rospkg;s = rospkg.RosPack();ret = s.get_path('rosbash');print(ret)"

about:
  home: http://www.ros.org/wiki/rosbash
  summary: |
    Assorted shell commands for using ros with bash.
  description: |
    Assorted shell commands for using ros with bash.
  license: BSD-3-Clause
  license_file: package.xml

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - seanyen
